/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bravest_ptt_androidlib_utils_JNIUtils */

#define APPLICATION_ID "ce21dd4747a54ca096dd4d93f5ef4fac"
#define REST_API_KEY "8aae60a7dd7112f6a69683e9593991db"

#ifndef _Included_bravest_ptt_androidlib_utils_JNIUtils
#define _Included_bravest_ptt_androidlib_utils_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bravest_ptt_androidlib_utils_JNIUtils
 * Method:    getApplicationId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bravest_ptt_androidlib_utils_JNIUtils_getApplicationId
        (JNIEnv *env, jclass class)
{
    return (*env)->NewStringUTF(env,APPLICATION_ID);
}

/*
 * Class:     bravest_ptt_androidlib_utils_JNIUtils
 * Method:    getRestAPIKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bravest_ptt_androidlib_utils_JNIUtils_getRestAPIKey
        (JNIEnv *env, jclass class)
{
    return (*env)->NewStringUTF(env,REST_API_KEY);
}

#ifdef __cplusplus
}
#endif
#endif


