/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bravest_ptt_androidlib_utils_JNIUtils */

#define APPLICATION_ID "e97765442849e06baa0db1d88632cbbe"
#define REST_API_KEY "8d0a9f45df408c1ca02f7b699ae3d032"

#ifndef _Included_bravest_ptt_androidlib_utils_JNIUtils
#define _Included_bravest_ptt_androidlib_utils_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bravest_ptt_androidlib_utils_JNIUtils
 * Method:    getApplicationId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bravest_ptt_androidlib_utils_JNIUtils_getApplicationId
        (JNIEnv *env, jclass class)
{
    return (*env)->NewStringUTF(env,APPLICATION_ID);
}

/*
 * Class:     bravest_ptt_androidlib_utils_JNIUtils
 * Method:    getRestAPIKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bravest_ptt_androidlib_utils_JNIUtils_getRestAPIKey
        (JNIEnv *env, jclass class)
{
    return (*env)->NewStringUTF(env,REST_API_KEY);
}

#ifdef __cplusplus
}
#endif
#endif


