/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bravest_ptt_androidlib_utils_JNIUtils */

#ifndef _Included_bravest_ptt_androidlib_utils_JNIUtils
#define _Included_bravest_ptt_androidlib_utils_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bravest_ptt_androidlib_utils_JNIUtils
 * Method:    getApplicationId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bravest_ptt_androidlib_utils_JNIUtils_getApplicationId
  (JNIEnv *, jclass);

/*
 * Class:     bravest_ptt_androidlib_utils_JNIUtils
 * Method:    getRestAPIKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bravest_ptt_androidlib_utils_JNIUtils_getRestAPIKey
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
